server:
  port: 8084
spring:
  application:
    name: customer
  datasource:
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      hibernate:
        ddl-auto: update
        show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    username: 'jimaloo'
    url: jdbc:postgresql://localhost:5432/customer
    password: 'password'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
